<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
      <LangVersion>latest</LangVersion>
      <SignAssembly>true</SignAssembly>
      <AssemblyOriginatorKeyFile>..\..\..\..\reqnroll.snk</AssemblyOriginatorKeyFile>
      <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <!-- Required for ConnectorJsonSerialization on netstandard2.0 targets -->
    <PackageReference Include="System.Text.Json" Version="9.*" />
  </ItemGroup>

</Project>
