package net.reqnroll.idesupport.rider.structureview

import com.intellij.openapi.project.Project
import com.intellij.openapi.util.Disposer
import com.intellij.openapi.wm.ToolWindow
import com.intellij.openapi.wm.ToolWindowFactory
import com.intellij.ui.content.ContentFactory

/**
 * Registers the "Reqnroll Structure" tool window — a dedicated Feature/Rule/Scenario/Step outline
 * for `.feature` files (issue #163), hosting a [StructureView][com.intellij.ide.structureView.StructureView]
 * built directly from [ReqnrollFeatureStructureViewBuilder] rather than through the platform's
 * declarative `com.intellij.structureViewBuilder` extension point.
 *
 * That EP was the first approach tried, and abandoned: it resolves through
 * `StructureViewBuilder.PROVIDER`, a JDK dynamic proxy generated by
 * `KeyedExtensionFactory`/`FileTypeExtensionFactory`, which throws a `ClassCastException` casting
 * our `StructureViewBuilderProvider` instance itself to `StructureViewBuilder` on Rider
 * 243.24978.27 (confirmed live via idea.log, and by decompiling the platform's own
 * `KeyedExtensionFactory` — our provider matched JetBrains' own
 * `LanguageFileTypeStructureViewBuilderProvider` byte-for-byte in shape, ruling out a registration
 * mistake on our side). [ReqnrollStructurePanel] calls
 * [ReqnrollFeatureStructureViewBuilder.createStructureView] directly instead: we already know
 * statically which builder applies to a `.feature` file, so no FileType-keyed EP lookup — and
 * therefore no proxy — is needed at all.
 */
class ReqnrollStructureToolWindowFactory : ToolWindowFactory {
    override fun createToolWindowContent(project: Project, toolWindow: ToolWindow) {
        val panel = ReqnrollStructurePanel(project)
        Disposer.register(toolWindow.disposable, panel)

        val content = ContentFactory.getInstance().createContent(panel.component, null, false)
        toolWindow.contentManager.addContent(content)
    }
}
